blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/alopesmendes/TodoistIA/discussions
    about: Use discussions for questions, ideas, and general conversation.